### ISSUE TITLE
Errors when running dev server

### ISSUE THREAD

**Issue by krokosik** [nuotsu/sanitypress#68]
Hi,
I wanted to migrate from the NextJS 14 to Sanity Press 7.0.8 and while everything builds successfully, the `dev` server seems to be somehow broken for me. I reverted back to commit `d484043ed02bf1dedbeaae681f33cbefa42d03af` and tried running everything there, but experience the same error, so it seems the issue is not in my code (I also tried removing the `.next` cache files and running `npm ci`).

I also tried running both Node 22 and 20 (I'm using Windows).

In the case of regular `dev` everything seems to work, but I keep getting a cryptic error message on each saved file that obscures the console output:
```
GET /worker-development.js 404 in 434ms
[TypeError: controller[kState].transformAlgorithm is not a function]
GET /workbox-8817a5e5.js 404 in 690ms
```

Like I said, everything works, but it is just annoying and I could not find any fix for it online.

One of the biggest reasons for me to update was Turbopack and unfortunately, in this case the dev server does not work at all with a different error message:
```
 ⨯ Error: `draftMode` was called outside a request scope. Read more: https://nextjs.org/docs/messages/next-dynamic-api-wrong-context
    at getExpectedRequestStore (.next\server\edge\chunks\_c37d0a95._.js:14493:33)
    at draftMode (.next\server\edge\chunks\_c37d0a95._.js:16703:84)
    at fetchSanityLive (.next\server\edge\chunks\[root of the server]__afd2e00a._.js:158:28)
    at getTranslations (.next\server\edge\chunks\[root of the server]__afd2e00a._.js:314:175)
    at __TURBOPACK__default__export__ (.next\server\edge\chunks\[root of the server]__afd2e00a._.js:369:180)
    at <unknown> (.next\server\edge\chunks\_c37d0a95._.js:17031:26)
    at <unknown> (.next\server\edge\chunks\_c37d0a95._.js:6314:655)
 GET /sw.js 404 in 2ms
 GET /workbox-8817a5e5.js 404 in 2ms
```

What is worse, the error prevents me from actually running the webpage. I tried commenting out all the use cases of `draftMode` to no avail.

I also get this error in various browsers: Firefox, Edge and Chrome.

The only cause I have yet to rule out is the fact that I did not migrate my Sanity dataset yet, but I did not expect breaking changes there, especially ones that somehow cause draftMode to be called incorrectly? Did you have similiar issues?

**Comment by nuotsu** [comment]
@krokosik Hi, I do remember seeing the `draftMode` error when updating from Next 14 to 15. The fix for me was a 2-parter:

1. Update the `fetchSanity` file
  - add `'use server'` at the top
  - make sure to `await` any `draftMode()` calls
  - you can reference the updated file here: https://github.com/nuotsu/sanitypress/blob/dev/src/sanity/lib/fetch.ts
2. (Most important) Replace all imports of the `groq` helper function from the `fetch.ts` file above to the `next-sanity` pkg.
  - there's quite a number of files where this need to be updated, but this will most likely fix the issue you are seeing:

```diff
- import { groq, fetchSanity } from '@/sanity/lib/fetch'
+ import { groq } from `next-sanity
```

Hope that solves it! 🤞

**Comment by krokosik** [comment]
I am using the Sanity Press version with all those fixes already in place and the problem still persists unfortunately :/

**Comment by krokosik** [comment]
I tried it with the demo dataset as well, together with the latest 7.1.0 release (no modifications of my own)

**Comment by krokosik** [comment]
Okay, the regular dev server works on the demo dataset so it seems, that the `[TypeError: controller[kState].transformAlgorithm is not a function]` issue is on my end. However, I found out that when using Turbopack, the `draftMode` error goes away when I comment out the `sanityFetch` call, so it's not the issue with the `draftMode` call there.

I can see that it is implemented in the same way as in Sanity docs, so I have no clue on how to progress.

**Comment by krokosik** [comment]
The `[TypeError: controller[kState].transformAlgorithm is not a function]` was actually not gone, but I found a fix for it!
It was caused by the old Next 14 service worker that had to be manually unregistered from the browser. Now it's just the turbopack that is broken for me. I have 2 issues in total with it:

1. the aforementioned draftMode. I worked around it by commenting out the `getTranslations` logic
2. Problem with `details-content` pseudo element. It seems that this prop is not properly polyfilled and I get a CSS parse error. Still, it also only happens with Turbopack and the production build runs fine, so I just comment it out for dev work.

I also had another issue, this time in production builds on Linux (previous attempts were on Windows), where deployments on Vercel failed due to `Error: Cannot find module '../lightningcss.linux-x64-gnu.node'`
Deleting package-lock and making a new one helped.
